### ISSUE TITLE
MPPC cutoff threshold and using biological replicates with Peaky

### ISSUE THREAD

**Issue by mbmoyo** [cqgd/pky#1]
I have been testing out Peaky and I have a few questions:

 1) Is there a formal method you are using to determine the cutoff value for the MPPC /or sqrt(MPPC) that would be used to subset the direct contacts from collateral contacts? Is it sufficient to simply list the contacts that account for >50% of the posterior or is there a final score (similar to CHiCAGO) that you assign to each contact after running Peaky? 

2) Is Peaky able to use biological replicates in the calculation of the mean contact strength or the MPPC? I imagine, for 3 replicates, it would require providing an interactions_file of the format: 
baitID preyID N1 N2 N3.

If replicates are not supported, would it suffice to simply run Peaky individually on each replicate and then look at the overlap of contacts that pass a specified threshold in each replicate to get a consensus list of direct contacts? I am thinking this would be preferable to pooling the raw counts from the individual replicates and using that as the N in the interactions_file?

3) Am I correct in stating that Peaky is best suited to run a few specific baits at a time? Would it be possible to calculate MPPC values for all bait-prey contacts in a capture Hi-C experiment at once? I noticed the wrapper scripts which take a baitlist. I am not quite clear how this would work in parallel on a scheduler given that you would likely be computing MPPCs associated with over 10000 baits. Or is this where a for loop would be better?

I guess what I am trying to determine is, in similar fashion to CHiCAGO, given an input file (baitID preyID N) of raw counts for all bait-prey contacts, how would you compute the MPPC for every contact in the input file and come away with a resulting filtered list of only direct contacts (and not collateral contacts) for all the baits in the capture Hi-C experiment without doing it in a bait-by-bait fashion as illustrated in the vignette? 

Thanks!

**Comment by cqgd** [comment]
Hi mbmoyo, thank you for your questions. This is just to let you know I'll get back to you with an extensive answer on Monday.

**Comment by cqgd** [comment]
1. For each putative contact, the MPPC is the final result of the analysis. As the MPPC is directly interpretable as a probability (one of the advantages of our method), no score is provided. While there is no formal method to determine a cut-off, you may want to ensure that the threshold you use leads you to find a subset of CHiCAGO’s calls.

Here’s another approach that may be of interest: suppose a contact occurs at either fragment A, B, or C, but we don’t know where exactly. RJMCMC samples models in which one of the three is always exclusively involved. Individually, each fragment may only have an MPPC of 33%, so we might not call a contact for any of the fragments, but the set as a whole definitely harbors a contact at A, B or C. We could find sets of modules like {A,B,C}, likely to contain a contact, by clustering based on fragment inclusion (here, the inclusion of A, B, C is correlated in the RJMCMC models). Then, for each set, we can find the probability of it containing at least one contact (i.e. the proportion of RJMCMC models in which one or more of the fragments of the set were involved). You could then report your top sets.

2. Pooling reads across biological replicates in Hi-C (and 5C) experiments appears to be fairly standard (see e.g. [here](https://www.bioconductor.org/packages/devel/data/experiment/vignettes/LiebermanAidenHiC2009/inst/doc/LiebermanAidenHiC2009.pdf) or [here](http://mirnylab.mit.edu/public/metaphase_supplement_highRes.pdf)) , and it’s also what we have done for our paper. This would make it less likely your initial negative binomial regression models (from _model_bin()_)will be overfitted. In the extreme case, if you'd have many of replicates with low read counts, this regression may not even work for any of them individually, or only be reasonable for short-range contacts (where readcounts are generally still high).

3. The filesystem wrapper is indeed relevant, and you are right that you would tell your cluster to process 10k baits or more using a single command. The number that is actually processed simultaneously would depend on the resources available, but this should ideally be handled by the scheduler on your cluster. In our case, around ~300 baits would regularly be processed simultaneously as part of a [SLURM array job](https://slurm.schedmd.com/job_array.html), where the [array index would be passed on](https://sph.umich.edu/biostat/computing/cluster/examples/r.html) as the index argument to _peaky_fs()_, and subsequently determine which bait to load. Your analysis would still occur in a bait-by-bait fashion, as it is in fact this separation into bait-wise problems that allows for parallelization.

Let me know if you need any further help, happy to discuss!

**Comment by jmbeesley** [comment]
Hi 

Regarding point 2, can I just check that the following would be an appropriate first step in combining biological replicates:
- Take chinput files generated for each library via the bam2chicago.sh script, deriving baitID preyID N
- Combine individual samples by grouping baitID-preyID, then summing N.

thanks for your help.
