### ISSUE TITLE
combining replicates using CHiCAGO input files

### ISSUE THREAD

**Issue by jmbeesley** [cqgd/pky#2]
Hi

Just hoping to get a couple of tips.

Regarding biological replicates - would the following be an appropriate first step in combining replicates:

- Take chinput files generated for each library via the bam2chicago.sh script, deriving baitID preyID N,
- Combine individual samples by grouping baitID-preyID for all samples, then summing N.

Thanks for your help.

JB

**Comment by cqgd** [comment]
Hi JB,

Pooling reads across like that seems perfectly fine to me (see also [point 2 in this other issue](https://github.com/cqgd/pky/issues/1#issuecomment-381692508)). 

It would also be sensible to remove reads where neither end of a pair can be aligned to a bait sequence (see also the section on CHiCAGO input files [here](https://osf.io/nemc6/wiki/home/)), if bam2chicago.sh doesn't already do this automatically.

Let me know if you need any additional information.

Chris

**Comment by jmbeesley** [comment]
Thanks Chris, that's good to know.

I was also hoping for some advice on these other issues please:

We've done two experiments in several cell types, one using promoter baits, and the other reciprocal experiment using baits around SNPs from a very large fine-mapping meta-analysis. I've run all baits from both, and used 1E+7 iterations for all - is that satisfactory? or other additional checks, and possibly more iterations, needed for each bait? So far, I'm seeing very using results in terms of validation (ie. longs runs of interactions picking out small numbers of fragments containing SNP/enhancer). 

Is my understanding correct that peaky should be able to provide a probability of the most likely 'driver' interaction even when there are only two consecutive interacting fragments? Just wondering because the examples in the paper focus on regions with much longer runs.

Thanks again,
JB

**Comment by cqgd** [comment]
Hi JB,

Sounds good. To check whether the number of iterations you've chosen is high enough, you could see if the MPPC values are stable by re-running the analysis (with an equal number of iterations) for a set of baits, and finding the correlation between the two sets of MPPC values you have obtained. We did this for all baits, and required 0.75 as the minimum (observing higher correlation in almost all cases). You could selectively increase the number of iterations for baits not meeting your MPPC correlation threshold. 

If instead you'd like to assess convergence based on the reversible-jump MCMC model coefficients, you could access them via `peaky_result@mcmc.output[,"P1234"]`, where `peaky_result` is returned by `peaky()`, and "P1234" refers to a (re-indexed) prey fragment.

Also, yes, gaps in the runs are not an issue, as long as there are ultimately enough counts to which the decay function (or peak) can be fitted. If you have two consecutive fragments with high read counts, no data for a number of fragments on either side, and then another set of counts further away, the analysis should work fine. However, in a scenario where you just have these two consecutive counts, and no other counts (>1) whatsoever, fitting a peak would not be reasonable. As such, we only processed baits with a minimum of 50 counts for all its preys in a 10MB region. For larger regions (or in case the counts are all very low), it would be wise to raise this threshold.

Hope this helps.

Chris

**Comment by jmbeesley** [comment]
Thanks Chris, that makes sense.

Is there a way to 're-start' a peaky_fs run from the 1e7 iterations, or does it need to start from 0?
Also, does the package include functions to test the correlation of parallel runs? 

And regarding the situation in which consecutive interacting fragments with spikes in MPPC are split by many fragments of very low MPPC, are you able to compare those results directly? For example, if we're seeing two peaks - one at 0.6 - and another say 30 fragments away at 0.2 - can we interpret that as the first being a more likely interaction than the second? 

thanks!
Jonno

**Comment by cqgd** [comment]
Hi Jonno,

While theoretically the RJMCMC process that `peaky()` uses could continue from a known state, e.g. the last model model sampled in your old `peaky()` results, a practical way to do this is currently not implemented.  That said, assuming that the burn-in phase of the process (i.e. the number of iterations needed for the model coefficients to reach equilibrium, after which models producing higher likelihoods tend to get sampled) is comparatively short with respect to the total number of iterations you are doing, you are not wasting much computational power by starting over. I would expect this to be the case for 1e7 iterations.

You could calculate the MPPC cor for all of `interpret_peaky()`’s output across two separate directories. Each directory should store the interpreted results for either your original or your re-run with peaky()). Here’s an [example](https://github.com/cqgd/mppc_cor_demo/blob/master/MPPC_cor.R). Data are in the same repo if you’d like to try it out. 

Yes, you can compare MPPC values directly, so your conclusion would be correct. You could even compare MPPC of preys across different baits. An exception would be if the baits were analyzed using different omegas, or if the model space priors used with peaky did not give you equal a priori belief in a given prey being a truly interacting fragment between different baits. The latter scenario would not occur unless peaky’s internal code was manually edited.

Feel free to ask if you have any further questions.

Chris

**Comment by jmbeesley** [comment]
Thanks once again Chris.

The correlation check will be straightforward with your code.
One further question - should the omega value be estimated for each specific bait? Just concerned that the default value of -5 which I've used for all baits may not be appropriate for all?

Thanks,
Jonno

**Comment by cqgd** [comment]
Hi Jonno,
 
I’ll preface this by saying we used a single omega value for all baits. We based several guesses on peaks we believed to result from direct contacts (as described in the vignette), and ultimately picked the value which yielded sensible residuals <sup>1</sup> (i.e. following the standard normal distribution) for the RJMCMC models across all baits. 
 
You could use a similar approach, but find that you actually obtain nicer RJMCMC residuals, more closely following the standard normal, by using different omega values for different baits. However, doing so could make it difficult to compare MPPC values between baits. As an example, imagine two extremely similar, neighboring baits which have the same CHi-C signal. With different values of omega for these baits, you may get different MPPC values for a given prey fragment, but to claim one bait fragment is more likely than the other to contact it directly seems dubious. There is no reason to suspect different rates of signal decay for the contacts made by these very similar baits, and so if they share the same signal around a prey, surely their MPPC for that prey should be equal (as it would have been if the same omega value had been used for both).
 
That said, we can certainly think of cases where varying omega, and subsequently still comparing MPPC values between baits, seems reasonable. For example, if cross-linking accuracy is spatially dependent (e.g. if certain regions experience crude crosslinking between groups of fragments at once), then the breadth of a peak marking a direct contact may change between baits in different locations. The same is true if the baits mark enhancers or promoters with varying levels of contact specificity. A contact that only needs to be approximate may be indicated by relatively broad peak after you’ve pooled counts from different cells together. It seems like a good idea to consider whether these assumptions hold when comparing MPPC values of baits analyzed with different omega values.
 
We’d be interested in ways of automatically finding appropriate omega values, so if you have any further thoughts we’d be happy to know.
 
Chris
 
<sup>1</sup> Note that we are fitting the RJMCMC models (built with `peaky()`) to the residuals of the negative-binomial regression models (built with `model_bin()`), a.k.a. NB residuals in the paper. The NB residuals are stored in `peaky_result_interpreted$residual`, so the RJMCMC model residuals would be defined as `peaky_result_interpreted$residual - peaky_result_interpreted$predicted`. I’m happy to provide more code for you to inspect these, if you need it.

**Comment by jmbeesley** [comment]
Hi Chris 
That's very helpful. I think we're best off leaving the omega constant as one of the main aims of our analysis is to make some calls on likely interaction targets across loci.
thanks,
Jonno

**Comment by jmbeesley** [comment]
Hi Chris

Just another quick question - in the preprint, you say that the "_The union of samples from both chains was used for inference_". Just wondering how this works? Wouldn't this lead to bait-prey pairs having 2 MPPC values in many cases? 

Thanks
Jonno

**Comment by cqgd** [comment]
Hi Jonno,

Sure! You are right in that we initially obtain two sets of models (from chain A and B), and that these are used to calculate two sets of MPPC values between which we calculate the correlation.

However, when the chains A and B have both converged, then the two sets of models should describe the same posterior distribution of peak heights (which leads to a high MPPC correlation). When we pool the models from chain A and B, we are still describing that same posterior distribution -- but in more detail, as we have more sampled values for each peak height. This provides an opportunity to make use of the extra chain generated to check for convergence!

If you'd like to try it out yourself, I've written some [example code](https://github.com/cqgd/mppc_cor_demo/blob/master/merge_chains_by_dir.R) which merges chains for all results (baits) stored across two different directories.

Please note that when you are looking at a merged chain produced by the code above, the first few models of chain B are not found in the first few rows of `@mcmc.output`. Rather, they appear further down, after the last models (rows) derived from chain A. This is important only if you want to discard the initial models from each chain as burn-in (which appeared unnecessary with the models we had sampled, as per Figure 4 in the [supplement](https://www.biorxiv.org/content/biorxiv/suppl/2018/01/11/243642.DC2/243642-2.pdf)).

Let me know if you need any further help.

Chris

**Comment by jmbeesley** [comment]
Great, thank you Chris! Running the code now.

And can I just ask a question of interpretation - for many baits, we're seeing clear peaks at positions that make sense (for example sites of relevant TF binding, fragments containing our GWAS variants etc). My questions are:
1) is it appropriate to apply some sort of MPPC threshold so that, for example MPPC values >0.1 are considered? Or would you suggest its more along the lines of considering framgents which show a dramatically increased MPPC above its neighbouring fragments?

2) and a related question: should we only be focussing on the fragments where the MPPC value 'peaks'? Or can a fragment contributing to the 'side of a peak', while still with a high MPPC, be of note? For example, a peak may just be off-centre relative to a fragment containing risk variants, while still exhibiting a high MPPC. I hope these make sense!

Thanks!
Jonno

**Comment by cqgd** [comment]
Hi Jonno,

Given that Peaky considers spatial patterns in the (normalized) read counts across neighboring fragments, it should not be necessary to look at changes relative to the local environment once again when one interprets the MPPC values. As such, thresholding the values directly is indeed an option (as discussed under [point 1 in this issue](https://github.com/cqgd/pky/issues/1#issuecomment-381692508), along with an alternative). In line with this, the shoulders of a peak in MPPC values can certainly be of interest, provided they still have high MPPC!  

One could imagine a peak in MPPC values resulting from a peak in the adjusted read counts above a series of neighboring fragments that can either be explained through a direct contact in the middle, or as  the summed result of two direct contacts on either side of the middle. If decomposition into two direct contacts is only slightly less probable than there being a central contact, we would be presented with a high central MPPC value and lower MPPC values on either side (i.e. as the MPPC peak shoulders). In this example, the shoulder MPPC values reflect the 'two direct contact peaks' scenario, which --depending on the absolute MPPC values-- could certainly be of interest.

If you have any further questions, or general comments about your findings, it'd be good to hear!

Chris

**Comment by jmbeesley** [comment]
Hi Chris

That all makes sense to me. 
We're wrapping up our paper now, which now includes the results from Peaky and I think shows how useful the method can be. For example, we've been looking at how we can further prioritise statistically indistinguishable risk-associated SNPs identified in our large fine-mapping study. We illustrate this with several  examples which are supported with functional data.

Thanks for all your answers!

Jonno

**Comment by cqgd** [comment]
Hi Jonno,

Using the high resolution chromatin interaction data that Peaky produces to prioritize GWAS hits is certainly exciting. Hope you will notify us when your work is out, would be very glad to read it!

Best wishes,

Chris
