### ISSUE TITLE
Error while estimating omega

### ISSUE THREAD

**Issue by maharshi14** [cqgd/pky#5]
Hi,

I'm following the vignette to estimate the omega parameter to describe the steepness of the peaks, but depending on the random baitID I choose, I get two kinds of error while I run the following code from the introduction:

dist_exp <- function(offset, strength, omega_power){
  omega <- 10^omega_power
  strength * exp(-(abs(offset * omega)))
}

fit_omega <- nls(residual~dist_exp(distance_from_peak,strength,omega_power), data=single_peak, start=list(strength=5, omega_power=-3))

{
plot(single_peak$distance_from_peak, single_peak$residual, main=paste0("Decay of signal for an isolated peak\nEstimate of omega = 10^", round(coefficients(fit_omega)["omega_power"],3)), xlab="Distance from center of peak (bp)", ylab="Adjusted readcount")
lines(single_peak$distance_from_peak, fitted.values(fit_omega), col="red", lwd=3)
}

Error 1:

Error in nls(residual ~ dist_exp(distance_from_peak, strength, omega_power),  :    singular gradient

Error 2:

Error in numericDeriv(form[[3L]], names(ind), env) : 
  Missing value or an infinity produced when evaluating the model

Not sure why they come up. Any troubleshoot on this would be very kind!

Thanks!

**Comment by cqgd** [comment]
Estimating the steepness of signal decay around a true interaction via `nls()` may fail when it is difficult to identify a good bona fide peak in your data. This may then require fiddling with the starting parameters (strength=5, omega_power=-3). Though, in my experience with datasets generated using various restriction enzymes, omega always ends up in the range of -3.5 to -5. 

It may also be worth running the next steps in the pipeline with a value in this range and testing whether peaks found look senssible using [peaky_plot](https://cqgd.github.io/pky/reference/peaky_plot.html). If omega is severely misspecified, you will see a flat predicted signal (green line). If you have found an appropriate value, the predicted signal will track your adjusted read counts.
